-- =========================================
-- Launch Test System (D1 / SQLite) Schema v1.1
-- IDs are TEXT (ULID/UUID string generated by app)
-- JSON is stored as TEXT (validate in application layer)
-- Timestamps: ISO8601 UTC string by default
-- =========================================

PRAGMA foreign_keys = ON;

-- ---------------------------
-- Core: tenants / users / memberships
-- ---------------------------
CREATE TABLE IF NOT EXISTS tenants (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  slug            TEXT NOT NULL UNIQUE,              -- used for subdomain or tenant key
  plan_key        TEXT NOT NULL DEFAULT 'free',
  settings_json   TEXT NOT NULL DEFAULT '{}',
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE,
  name            TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- role: owner|operator|reviewer|viewer
-- status: active|invited|disabled
CREATE TABLE IF NOT EXISTS memberships (
  tenant_id       TEXT NOT NULL,
  user_id         TEXT NOT NULL,
  role            TEXT NOT NULL CHECK (role IN ('owner','operator','reviewer','viewer')),
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','invited','disabled')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (tenant_id, user_id),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_memberships_tenant ON memberships(tenant_id);

-- ---------------------------
-- Projects
-- ---------------------------
CREATE TABLE IF NOT EXISTS projects (
  id                 TEXT PRIMARY KEY,
  tenant_id           TEXT NOT NULL,
  name               TEXT NOT NULL,

  -- business config
  offer_json          TEXT NOT NULL DEFAULT '{}',
  cv_definition_json  TEXT NOT NULL DEFAULT '{}',

  -- requested JSON schema target
  ng_rules_json       TEXT NOT NULL DEFAULT '{}',

  -- optional
  brand_json          TEXT NOT NULL DEFAULT '{}',

  -- form config: internal|external_redirect|webhook_submit
  form_config_json    TEXT NOT NULL DEFAULT '{}',

  default_disclaimer  TEXT NOT NULL DEFAULT '',

  archived_at         TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_projects_tenant ON projects(tenant_id);

-- project assets stored in R2
CREATE TABLE IF NOT EXISTS project_assets (
  id            TEXT PRIMARY KEY,
  project_id    TEXT NOT NULL,
  asset_type    TEXT NOT NULL,             -- e.g. logo|evidence|image|pdf|other
  r2_key        TEXT NOT NULL,
  meta_json     TEXT NOT NULL DEFAULT '{}',
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_project_assets_project ON project_assets(project_id);

-- ---------------------------
-- Runs / Intents
-- ---------------------------
-- status: Draft|Designing|Generating|ReadyForReview|Approved|Publishing|Live|Running|Paused|Completed|Archived
-- operation_mode: manual|hybrid|auto
CREATE TABLE IF NOT EXISTS runs (
  id                     TEXT PRIMARY KEY,
  project_id              TEXT NOT NULL,
  name                   TEXT NOT NULL,

  status                 TEXT NOT NULL DEFAULT 'Draft',
  operation_mode         TEXT NOT NULL DEFAULT 'manual' CHECK (operation_mode IN ('manual','hybrid','auto')),

  start_at               TEXT,
  end_at                 TEXT,

  -- requested JSON schema target
  run_design_json        TEXT NOT NULL DEFAULT '{}',

  -- Stop Condition DSL (JSON)
  stop_dsl_json          TEXT NOT NULL DEFAULT '{}',

  -- Fixed/Explore granularity config (JSON)
  fixed_granularity_json TEXT NOT NULL DEFAULT '{}',

  -- decision config (JSON), optional
  decision_rules_json    TEXT NOT NULL DEFAULT '{}',

  created_by_user_id     TEXT,
  created_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  approved_at            TEXT,
  published_at           TEXT,
  launched_at            TEXT,
  completed_at           TEXT,

  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_runs_project ON runs(project_id);
CREATE INDEX IF NOT EXISTS idx_runs_status ON runs(status);
CREATE INDEX IF NOT EXISTS idx_runs_mode ON runs(operation_mode);

-- status: active|paused|archived
CREATE TABLE IF NOT EXISTS intents (
  id             TEXT PRIMARY KEY,
  run_id         TEXT NOT NULL,
  title          TEXT NOT NULL,
  hypothesis     TEXT NOT NULL DEFAULT '',
  evidence_json  TEXT NOT NULL DEFAULT '{}',
  faq_json       TEXT NOT NULL DEFAULT '{}',
  priority       INTEGER NOT NULL DEFAULT 0,
  status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','archived')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_intents_run ON intents(run_id);
CREATE INDEX IF NOT EXISTS idx_intents_priority ON intents(run_id, priority);

-- ---------------------------
-- Variants: LP / Creative / Ad Copy
-- ---------------------------
-- approval_status: draft|submitted|approved|rejected
CREATE TABLE IF NOT EXISTS lp_variants (
  id               TEXT PRIMARY KEY,
  intent_id         TEXT NOT NULL,
  version           INTEGER NOT NULL DEFAULT 1,
  status            TEXT NOT NULL DEFAULT 'draft',     -- draft|ready|published|archived
  blocks_json       TEXT NOT NULL DEFAULT '{}',
  theme_json        TEXT NOT NULL DEFAULT '{}',
  qa_result_json    TEXT NOT NULL DEFAULT '{}',

  approval_status   TEXT NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft','submitted','approved','rejected')),
  approved_hash     TEXT,                              -- hash of the approved content snapshot

  published_url     TEXT,
  snapshot_r2_key   TEXT,                              -- manifest/html snapshot key
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lp_variants_intent ON lp_variants(intent_id);
CREATE INDEX IF NOT EXISTS idx_lp_variants_approval ON lp_variants(approval_status);

CREATE TABLE IF NOT EXISTS creative_variants (
  id               TEXT PRIMARY KEY,
  intent_id         TEXT NOT NULL,
  size              TEXT NOT NULL CHECK (size IN ('1:1','4:5','9:16')),
  version           INTEGER NOT NULL DEFAULT 1,
  status            TEXT NOT NULL DEFAULT 'draft',     -- draft|ready|archived
  text_layers_json  TEXT NOT NULL DEFAULT '{}',
  image_r2_key      TEXT NOT NULL,                    -- required
  qa_result_json    TEXT NOT NULL DEFAULT '{}',

  approval_status   TEXT NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft','submitted','approved','rejected')),
  approved_hash     TEXT,

  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_creative_variants_intent ON creative_variants(intent_id);
CREATE INDEX IF NOT EXISTS idx_creative_variants_size ON creative_variants(size);
CREATE INDEX IF NOT EXISTS idx_creative_variants_approval ON creative_variants(approval_status);

CREATE TABLE IF NOT EXISTS ad_copies (
  id               TEXT PRIMARY KEY,
  intent_id         TEXT NOT NULL,
  version           INTEGER NOT NULL DEFAULT 1,
  status            TEXT NOT NULL DEFAULT 'draft',
  primary_text      TEXT NOT NULL DEFAULT '',
  headline          TEXT NOT NULL DEFAULT '',
  description       TEXT NOT NULL DEFAULT '',
  qa_result_json    TEXT NOT NULL DEFAULT '{}',

  approval_status   TEXT NOT NULL DEFAULT 'draft' CHECK (approval_status IN ('draft','submitted','approved','rejected')),
  approved_hash     TEXT,

  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ad_copies_intent ON ad_copies(intent_id);
CREATE INDEX IF NOT EXISTS idx_ad_copies_approval ON ad_copies(approval_status);

-- Approval records (auditable)
-- target_type: run|lp_variant|creative_variant|ad_copy|deployment|meta_config
CREATE TABLE IF NOT EXISTS approvals (
  id              TEXT PRIMARY KEY,
  tenant_id        TEXT NOT NULL,
  target_type      TEXT NOT NULL,
  target_id        TEXT NOT NULL,
  status           TEXT NOT NULL CHECK (status IN ('submitted','approved','rejected')),
  reviewer_user_id TEXT,
  comment          TEXT NOT NULL DEFAULT '',
  target_hash      TEXT NOT NULL, -- content hash at approval time
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_approvals_target ON approvals(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_approvals_tenant ON approvals(tenant_id);

-- ---------------------------
-- Deployments / URLs
-- ---------------------------
CREATE TABLE IF NOT EXISTS deployments (
  id                      TEXT PRIMARY KEY,
  run_id                  TEXT NOT NULL,
  status                  TEXT NOT NULL DEFAULT 'draft', -- draft|published|rolled_back|archived
  urls_json               TEXT NOT NULL DEFAULT '{}',
  snapshot_manifest_r2_key TEXT,  -- points to published snapshot manifest
  created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_deployments_run ON deployments(run_id);

-- ---------------------------
-- Meta connections / entities / bundles
-- ---------------------------
-- status: active|revoked|error
CREATE TABLE IF NOT EXISTS meta_connections (
  id               TEXT PRIMARY KEY,
  tenant_id         TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked','error')),
  token_ref        TEXT NOT NULL,         -- reference to encrypted token in secret store / KV
  ad_account_id    TEXT,
  pixel_id         TEXT,
  page_id          TEXT,
  ig_user_id       TEXT,
  scopes_json      TEXT NOT NULL DEFAULT '[]',
  meta_json        TEXT NOT NULL DEFAULT '{}',
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_meta_connections_tenant ON meta_connections(tenant_id);

-- entity_type: campaign|adset|ad|creative
CREATE TABLE IF NOT EXISTS meta_entities (
  id            TEXT PRIMARY KEY,
  run_id        TEXT NOT NULL,
  intent_id     TEXT,
  entity_type   TEXT NOT NULL CHECK (entity_type IN ('campaign','adset','ad','creative')),
  local_ref     TEXT NOT NULL,      -- internal logical key for mapping
  remote_id     TEXT,               -- may be NULL in Manual Mode
  status        TEXT NOT NULL DEFAULT 'draft',
  meta_json     TEXT NOT NULL DEFAULT '{}',
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_meta_entities_run ON meta_entities(run_id);
CREATE INDEX IF NOT EXISTS idx_meta_entities_remote ON meta_entities(remote_id);

-- Ad Bundle ties LP + Creative + Copy (+ optional Meta IDs) + UTM
CREATE TABLE IF NOT EXISTS ad_bundles (
  id                  TEXT PRIMARY KEY,
  run_id              TEXT NOT NULL,
  intent_id           TEXT NOT NULL,
  lp_variant_id       TEXT NOT NULL,
  creative_variant_id TEXT NOT NULL,
  ad_copy_id          TEXT NOT NULL,

  utm_string          TEXT NOT NULL, -- canonical UTM string for tracking
  status              TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('ready','running','paused','archived')),

  -- optional meta mapping (NULL allowed for Manual Mode)
  meta_campaign_id    TEXT,
  meta_adset_id       TEXT,
  meta_ad_id          TEXT,

  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),

  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE CASCADE,
  FOREIGN KEY (lp_variant_id) REFERENCES lp_variants(id) ON DELETE CASCADE,
  FOREIGN KEY (creative_variant_id) REFERENCES creative_variants(id) ON DELETE CASCADE,
  FOREIGN KEY (ad_copy_id) REFERENCES ad_copies(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ad_bundles_run ON ad_bundles(run_id);
CREATE INDEX IF NOT EXISTS idx_ad_bundles_meta_ad ON ad_bundles(meta_ad_id);

-- ---------------------------
-- Events (first-party) + Insights (Meta or Manual import)
-- ---------------------------
-- event_type: pageview|cta_click|form_submit|form_success
CREATE TABLE IF NOT EXISTS events (
  id                  TEXT PRIMARY KEY,  -- event_id for dedupe
  tenant_id            TEXT NOT NULL,
  run_id              TEXT NOT NULL,
  intent_id           TEXT,
  lp_variant_id       TEXT NOT NULL,
  creative_variant_id TEXT,
  ad_bundle_id        TEXT,              -- optional, can be resolved by utm
  event_type          TEXT NOT NULL CHECK (event_type IN ('pageview','cta_click','form_submit','form_success')),
  ts_ms               INTEGER NOT NULL,  -- epoch ms

  session_id          TEXT NOT NULL,
  page_url            TEXT NOT NULL,
  referrer            TEXT,
  user_agent          TEXT,
  ip_hash             TEXT,              -- optional (hash server-side)

  meta_json           TEXT NOT NULL DEFAULT '{}',

  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  FOREIGN KEY (intent_id) REFERENCES intents(id) ON DELETE SET NULL,
  FOREIGN KEY (lp_variant_id) REFERENCES lp_variants(id) ON DELETE CASCADE,
  FOREIGN KEY (creative_variant_id) REFERENCES creative_variants(id) ON DELETE SET NULL,
  FOREIGN KEY (ad_bundle_id) REFERENCES ad_bundles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_events_run_ts ON events(run_id, ts_ms);
CREATE INDEX IF NOT EXISTS idx_events_lp_ts ON events(lp_variant_id, ts_ms);
CREATE INDEX IF NOT EXISTS idx_events_session_ts ON events(session_id, ts_ms);

-- Hourly metrics per bundle (from Meta Insights OR manual import)
CREATE TABLE IF NOT EXISTS insights_hourly (
  ad_bundle_id   TEXT NOT NULL,
  ts_hour        TEXT NOT NULL,          -- ISO hour: 2026-01-13T10:00:00Z
  metrics_json   TEXT NOT NULL DEFAULT '{}',
  source         TEXT NOT NULL DEFAULT 'meta' CHECK (source IN ('meta','manual')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (ad_bundle_id, ts_hour),
  FOREIGN KEY (ad_bundle_id) REFERENCES ad_bundles(id) ON DELETE CASCADE
);

-- Daily metrics per bundle
CREATE TABLE IF NOT EXISTS insights_daily (
  ad_bundle_id   TEXT NOT NULL,
  date_yyyy_mm_dd TEXT NOT NULL,         -- 2026-01-13
  metrics_json   TEXT NOT NULL DEFAULT '{}',
  source         TEXT NOT NULL DEFAULT 'meta' CHECK (source IN ('meta','manual')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (ad_bundle_id, date_yyyy_mm_dd),
  FOREIGN KEY (ad_bundle_id) REFERENCES ad_bundles(id) ON DELETE CASCADE
);

-- Manual import audit
CREATE TABLE IF NOT EXISTS manual_imports (
  id           TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL,
  run_id       TEXT NOT NULL,
  import_type  TEXT NOT NULL CHECK (import_type IN ('insights_csv','mapping_csv')),
  file_r2_key  TEXT NOT NULL,
  summary_json TEXT NOT NULL DEFAULT '{}',
  created_by_user_id TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_manual_imports_run ON manual_imports(run_id);

-- ---------------------------
-- Decisions / Incidents
-- ---------------------------
-- confidence: insufficient|directional|confident
CREATE TABLE IF NOT EXISTS decisions (
  id            TEXT PRIMARY KEY,
  run_id        TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','final')),
  confidence    TEXT NOT NULL DEFAULT 'insufficient' CHECK (confidence IN ('insufficient','directional','confident')),
  winner_json   TEXT NOT NULL DEFAULT '{}',
  ranking_json  TEXT NOT NULL DEFAULT '{}',
  stats_json    TEXT NOT NULL DEFAULT '{}',      -- e.g. CI/Bayes results, thresholds
  rationale     TEXT NOT NULL DEFAULT '',
  decided_at    TEXT,
  created_by_user_id TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_decisions_run ON decisions(run_id);

-- incident_type: meta_rejected|meta_account_issue|api_outage|measurement_issue|other
-- severity: low|medium|high|critical
-- status: open|mitigating|resolved
CREATE TABLE IF NOT EXISTS incidents (
  id            TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL,
  run_id        TEXT,
  incident_type TEXT NOT NULL,
  severity      TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
  status        TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','mitigating','resolved')),
  reason        TEXT NOT NULL DEFAULT '',
  meta_json     TEXT NOT NULL DEFAULT '{}',
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  resolved_at   TEXT,
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_incidents_tenant ON incidents(tenant_id);
CREATE INDEX IF NOT EXISTS idx_incidents_run ON incidents(run_id);

-- ---------------------------
-- Audit logs / Jobs / Notifications / Feature Flags
-- ---------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  id             TEXT PRIMARY KEY,
  tenant_id       TEXT NOT NULL,
  actor_user_id  TEXT,
  action         TEXT NOT NULL,          -- e.g. run.launch, approval.approve
  target_type    TEXT NOT NULL,
  target_id      TEXT NOT NULL,

  before_json    TEXT NOT NULL DEFAULT '{}',
  after_json     TEXT NOT NULL DEFAULT '{}',

  prev_hash      TEXT,
  hash           TEXT NOT NULL,
  request_id     TEXT NOT NULL,

  ts_ms          INTEGER NOT NULL,
  ip_hash        TEXT,
  user_agent     TEXT,

  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_tenant_ts ON audit_logs(tenant_id, ts_ms);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_logs(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_request ON audit_logs(request_id);

-- job_type: generate|qa_smoke|publish|meta_sync|stop_eval|report|notify|import_parse
-- status: queued|running|succeeded|failed|cancelled
CREATE TABLE IF NOT EXISTS jobs (
  id            TEXT PRIMARY KEY,
  tenant_id      TEXT NOT NULL,
  job_type      TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
  payload_json  TEXT NOT NULL DEFAULT '{}',
  result_json   TEXT NOT NULL DEFAULT '{}',
  attempts      INTEGER NOT NULL DEFAULT 0,
  max_attempts  INTEGER NOT NULL DEFAULT 10,
  last_error    TEXT NOT NULL DEFAULT '',
  scheduled_at  TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_jobs_tenant_status ON jobs(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_jobs_type_status ON jobs(job_type, status);

-- channel: email|slack|webhook
-- status: pending|sent|failed
CREATE TABLE IF NOT EXISTS notifications (
  id           TEXT PRIMARY KEY,
  tenant_id     TEXT NOT NULL,
  channel      TEXT NOT NULL CHECK (channel IN ('email','slack','webhook')),
  event_type   TEXT NOT NULL,
  payload_json TEXT NOT NULL DEFAULT '{}',
  status       TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
  sent_at      TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_tenant_status ON notifications(tenant_id, status);

-- Feature flags for gradual DB migration / mode toggles
CREATE TABLE IF NOT EXISTS tenant_flags (
  tenant_id    TEXT NOT NULL,
  flag_key     TEXT NOT NULL,
  value_json   TEXT NOT NULL DEFAULT '{}',
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (tenant_id, flag_key),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
