# Priority Labels
- name: "priority:P0-Critical"
  color: "B60205"
  description: "緊急度最高・即座に対応必要"
- name: "priority:P1-High"
  color: "D93F0B"
  description: "高優先度・24時間以内に対応"
- name: "priority:P2-Medium"
  color: "FBCA04"
  description: "中優先度・1週間以内に対応"
- name: "priority:P3-Low"
  color: "0E8A16"
  description: "低優先度・余裕があれば対応"

# State Labels
- name: "state:pending"
  color: "E4E669"
  description: "未着手・キューに入っている"
- name: "state:analyzing"
  color: "D4C5F9"
  description: "分析中・要件を調査中"
- name: "state:implementing"
  color: "1D76DB"
  description: "実装中・コード作成中"
- name: "state:reviewing"
  color: "5319E7"
  description: "レビュー中・確認待ち"
- name: "state:done"
  color: "0E8A16"
  description: "完了・クローズ可能"
- name: "state:blocked"
  color: "B60205"
  description: "ブロック中・外部要因で停止"
- name: "state:failed"
  color: "B60205"
  description: "失敗・対応が必要"

# Agent Labels
- name: "agent:coordinator"
  color: "6F42C1"
  description: "Coordinator Agent担当"
- name: "agent:codegen"
  color: "6F42C1"
  description: "CodeGen Agent担当"
- name: "agent:review"
  color: "6F42C1"
  description: "Review Agent担当"
- name: "agent:issue"
  color: "6F42C1"
  description: "Issue Agent担当"
- name: "agent:pr"
  color: "6F42C1"
  description: "PR Agent担当"
- name: "agent:deployment"
  color: "6F42C1"
  description: "Deployment Agent担当"
- name: "agent:test"
  color: "6F42C1"
  description: "Test Agent担当"

# Quality Labels
- name: "quality:excellent"
  color: "0E8A16"
  description: "品質優秀・ベストプラクティス"
- name: "quality:good"
  color: "1D76DB"
  description: "品質良好・基準を満たす"
- name: "quality:needs-improvement"
  color: "FBCA04"
  description: "改善必要・一部問題あり"
- name: "quality:poor"
  color: "B60205"
  description: "品質不良・大幅な改善が必要"

# Type Labels
- name: "type:feature"
  color: "A2EEEF"
  description: "新機能・新しい機能の追加"
- name: "type:bug"
  color: "D73A4A"
  description: "バグ・不具合の修正"
- name: "type:refactor"
  color: "0075CA"
  description: "リファクタリング・コード改善"
- name: "type:docs"
  color: "0075CA"
  description: "ドキュメント・文書の追加/更新"
- name: "type:test"
  color: "0075CA"
  description: "テスト・テストの追加/改善"
- name: "type:deployment"
  color: "0075CA"
  description: "デプロイ・リリース関連"
- name: "type:chore"
  color: "D4C5F9"
  description: "雑務・メンテナンス作業"
- name: "type:security"
  color: "B60205"
  description: "セキュリティ・脆弱性対応"
- name: "type:performance"
  color: "FBCA04"
  description: "パフォーマンス・性能改善"
- name: "type:ci"
  color: "0075CA"
  description: "CI/CD・自動化関連"

# Size Labels
- name: "size:XS"
  color: "C2E0C6"
  description: "極小・1-2時間以内"
- name: "size:S"
  color: "C2E0C6"
  description: "小・半日程度"
- name: "size:M"
  color: "FEF2C0"
  description: "中・1-2日程度"
- name: "size:L"
  color: "F9D0C4"
  description: "大・3-5日程度"
- name: "size:XL"
  color: "E99695"
  description: "特大・1週間以上"

# Complexity Labels
- name: "complexity:low"
  color: "C2E0C6"
  description: "低複雑度・シンプルな変更"
- name: "complexity:medium"
  color: "FEF2C0"
  description: "中複雑度・適度な複雑さ"
- name: "complexity:high"
  color: "F9D0C4"
  description: "高複雑度・複雑な実装"
- name: "complexity:critical"
  color: "E99695"
  description: "クリティカル・最高難易度"

# Status Labels
- name: "needs-triage"
  color: "D93F0B"
  description: "トリアージ必要・分類待ち"
- name: "needs-review"
  color: "5319E7"
  description: "レビュー必要・確認待ち"
- name: "needs-info"
  color: "D876E3"
  description: "情報不足・追加情報が必要"
- name: "good-first-issue"
  color: "7057FF"
  description: "初心者向け・入門に最適"
- name: "help-wanted"
  color: "008672"
  description: "ヘルプ募集・協力求む"
- name: "discussion"
  color: "D4C5F9"
  description: "議論・ディスカッション"
- name: "stale"
  color: "CFD3D7"
  description: "放置・アクティビティなし"
